server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: predio-service
          uri: lb://predio-service
          predicates:
            - Path=/predios/**
